version: '3.7'

services:
  node:
    build:
      context: ./
      dockerfile: docker/node/Dockerfile
    image: marketplace-api
    container_name: marketplace-api
    depends_on:
      - db
    env_file: .env
    environment:
      DB_HOST: db
    expose:
      - ${PORT}
    tty: true
    volumes:
      - /home/node/node_modules

  db:
    image: postgres:12.3
    container_name: marketplace-api-db
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: marketplace-api
    container_name: marketplace-api-migrate
    entrypoint: dockerize -wait tcp://db:{DB_PORT} -timeout 30s npm run db:migrate
    environment:
      DB_HOST: db
    depends_on:
      - db
      - node

volumes:
  db_data:
